// @flow strict
import {
  PLAYER_ATTACK_EVENT,
  PLAYER_PUT_BLOCK_EVENT,
  CAMERA_LOCK_EVENT,
  CAMERA_MOVED_EVENT,
  CAMERA_UNLOCKED_EVENT,
  PLAYER_MOVE_FORWARD_EVENT,
  PLAYER_MOVE_BACKWARD_EVENT,
  PLAYER_MOVE_LEFT_EVENT,
  PLAYER_MOVE_RIGHT_EVENT,
  PLAYER_RUN_EVENT,
  PLAYER_JUMP_EVENT,
  TOGGLE_MENU_EVENT,
  TOGGLE_INVENTORY_EVENT,
} from './eventTypes';
import {
  KEY_A,
  KEY_D,
  KEY_I,
  KEY_S,
  KEY_W,
  KEY_SPACE,
  KEY_ESCAPE,
  KEY_ARROW_UP,
  KEY_ARROW_DOWN,
  KEY_ARROW_LEFT,
  KEY_ARROW_RIGHT,
  KEY_SHIFT_LEFT,
} from './keyboardRawEvents';

import {
  MOUSE_MOVE,
  MOUSE_LEFT_BUTTON,
  MOUSE_POINTER_UNLOCKED,
  MOUSE_RIGHT_BUTTON,
} from './mouseRawEvents';

export default [
  [MOUSE_LEFT_BUTTON, CAMERA_LOCK_EVENT],
  [KEY_ESCAPE, TOGGLE_MENU_EVENT],

  [MOUSE_LEFT_BUTTON, PLAYER_ATTACK_EVENT],
  [MOUSE_RIGHT_BUTTON, PLAYER_PUT_BLOCK_EVENT],
  [MOUSE_MOVE, CAMERA_MOVED_EVENT],
  [MOUSE_POINTER_UNLOCKED, CAMERA_UNLOCKED_EVENT],
  [KEY_W, PLAYER_MOVE_FORWARD_EVENT],
  [KEY_S, PLAYER_MOVE_BACKWARD_EVENT],
  [KEY_A, PLAYER_MOVE_LEFT_EVENT],
  [KEY_D, PLAYER_MOVE_RIGHT_EVENT],
  [KEY_ARROW_UP, PLAYER_MOVE_FORWARD_EVENT],
  [KEY_ARROW_DOWN, PLAYER_MOVE_BACKWARD_EVENT],
  [KEY_ARROW_LEFT, PLAYER_MOVE_LEFT_EVENT],
  [KEY_ARROW_RIGHT, PLAYER_MOVE_RIGHT_EVENT],

  [KEY_SHIFT_LEFT, PLAYER_RUN_EVENT],
  [KEY_SPACE, PLAYER_JUMP_EVENT],
  [KEY_ESCAPE, TOGGLE_MENU_EVENT],
  [KEY_I, TOGGLE_INVENTORY_EVENT],
];
