// @flow
export const CAMERA_MOVED: 'CAMERA_MOVED' = 'CAMERA_MOVED';
export const CAMERA_LOCKED: 'CAMERA_LOCKED' = 'CAMERA_LOCKED';
export const CAMERA_UNLOCKED: 'CAMERA_UNLOCKED' = 'CAMERA_UNLOCKED';
export const PLAYER_MOVED: 'PLAYER_MOVED' = 'PLAYER_MOVED';
export const PLAYER_STOPED_MOVE: 'PLAYER_STOPED_MOVE' = 'PLAYER_STOPED_MOVE';
export const DIRECTION_FORWARD: 'DIRECTION_FORWARD' = 'DIRECTION_FORWARD';
export const DIRECTION_BACK: 'DIRECTION_BACK' = 'DIRECTION_BACK';
export const DIRECTION_LEFT: 'DIRECTION_LEFT' = 'DIRECTION_LEFT';
export const DIRECTION_RIGHT: 'DIRECTION_RIGHT' = 'DIRECTION_RIGHT';
export const PLAYER_JUMPED: 'PLAYER_JUMPED' = 'PLAYER_JUMPED';
export const PLAYER_RUN: 'PLAYER_RUN' = 'PLAYER_RUN';
export const PLAYER_STOPED_RUN: 'PLAYER_STOPED_RUN' = 'PLAYER_STOPED_RUN';
export const PLAYER_ATTACKED: 'PLAYER_ATTACKED' = 'PLAYER_ATTACKED';
export const PLAYER_STOPED_ATTACK: 'PLAYER_STOPED_ATTACK' = 'PLAYER_STOPED_ATTACK';
export const PLAYER_STARTED_DESTROYING_BLOCK: 'PLAYER_STARTED_DESTROYING_BLOCK' = 'PLAYER_STARTED_DESTROYING_BLOCK';
export const PLAYER_DESTROYED_BLOCK: 'PLAYER_DESTROYED_BLOCK' = 'PLAYER_DESTROYED_BLOCK';
export const PLAYER_START_PUT_BLOCK: 'PLAYER_START_PUT_BLOCK' = 'PLAYER_START_PUT_BLOCK';
export const PLAYER_PUT_BLOCK: 'PLAYER_PUT_BLOCK' = 'PLAYER_PUT_BLOCK';

type Event<Type, Payload> = {
  +type: Type,
  +payload: Payload,
}

export type PLAYER_DESTROYED_BLOCK_TYPE = Event<typeof PLAYER_DESTROYED_BLOCK, {
  +geoId: string,
  +x: number,
  +y: number,
  +z: number,
}>
