// @flow
export const PLAYER_LOADED: 'PLAYER_LOADED' = 'PLAYER_LOADED';
export const PLAYERS_UPDATED: 'PLAYERS_UPDATED' = 'PLAYERS_UPDATED';
export const PLAYER_CHANGED_ROTATION: 'PLAYER_CHANGED_ROTATION' = 'PLAYER_CHANGED_ROTATION';
export const PLAYER_CHANGE_POSITION: 'PLAYER_CHANGE_POSITION' = 'PLAYER_CHANGE_POSITION';
export const PLAYER_JUMPED: 'PLAYER_JUMPED' = 'PLAYER_JUMPED';
export const PLAYER_STOPED_JUMPING: 'PLAYER_STOPED_JUMPING' = 'PLAYER_STOPED_JUMPING';
export const PLAYER_STOPED_MOVING: 'PLAYER_STOPED_MOVING' = 'PLAYER_STOPED_MOVING';
export const PLAYER_RUN: 'PLAYER_RUN' = 'PLAYER_RUN';
export const PLAYER_STOPED_RUNING: 'PLAYER_STOPED_RUNING' = 'PLAYER_STOPED_RUNING';
export const DIRECTION_FORWARD: 'DIRECTION_FORWARD' = 'DIRECTION_FORWARD';
export const DIRECTION_BACK: 'DIRECTION_BACK' = 'DIRECTION_BACK';
export const DIRECTION_LEFT: 'DIRECTION_LEFT' = 'DIRECTION_LEFT';
export const DIRECTION_RIGHT: 'DIRECTION_RIGHT' = 'DIRECTION_RIGHT';
export const PLAYER_STARTED_REMOVE_BLOCK: 'PLAYER_STARTED_REMOVE_BLOCK' = 'PLAYER_STARTED_REMOVE_BLOCK';
export const PLAYER_STOPED_REMOVE_BLOCK: 'PLAYER_STOPED_REMOVE_BLOCK' = 'PLAYER_STOPED_REMOVE_BLOCK';
export const PLAYER_PLACED_BLOCK: 'PLAYER_PLACED_BLOCK' = 'PLAYER_PLACED_BLOCK';
