// @flow
export const MOUSE_MOVED: 'MOUSE_MOVED' = 'MOUSE_MOVED';
export const MOUSE_BUTTON_PRESSED: 'MOUSE_BUTTON_PRESSED' = 'MOUSE_BUTTON_PRESSED';
export const MOUSE_BUTTON_RELEASED: 'MOUSE_BUTTON_RELEASED' = 'MOUSE_BUTTON_RELEASED';
export const MOUSE_LOCK_CHANGED: 'MOUSE_LOCK_CHANGED' = 'MOUSE_LOCK_CHANGED';
export const MOUSE_BUTTON_LEFT: 0 = 0;
export const MOUSE_BUTTON_MIDDLE: 1 = 1;
export const MOUSE_BUTTON_RIGHT: 2 = 2;
