// @flow strict
export const HUD_DATA_UPDATED: 'HUD_DATA_UPDATED' = 'HUD_DATA_UPDATED';
export const MENU_TOGGLED: 'MENU_TOGGLED' = 'MENU_TOGGLED';
export const INVENTORY_TOGGLED: 'INVENTORY_TOGGLED' = 'INVENTORY_TOGGLED';
export const KEY_SELECT_BUTTON: 'KEY_SELECT_BUTTON' = 'KEY_SELECT_BUTTON';
