// @flow strict
export const NEXT_ITEM_SELECTED: 'NEXT_ITEM_SELECTED' = 'NEXT_ITEM_SELECTED';
export const PREVIOUS_ITEM_SELECTED: 'PREVIOUS_ITEM_SELECTED' = 'PREVIOUS_ITEM_SELECTED';
export const SWAP_MAIN_PANEL_ITEMS: 'SWAP_MAIN_PANEL_ITEMS' = 'SWAP_MAIN_PANEL_ITEMS';
export const DELETE_MAIN_PANEL_ITEMS: 'DELETE_MAIN_PANEL_ITEMS' = 'DELETE_MAIN_PANEL_ITEMS';
export const COPY_MAIN_PANEL_ITEMS: 'COPY_MAIN_PANEL_ITEMS' = 'COPY_MAIN_PANEL_ITEMS';
