export const SWAP_MAIN_PANEL_ITEMS: 'SWAP_MAIN_PANEL_ITEMS' = 'SWAP_MAIN_PANEL_ITEMS';
export const DELETE_MAIN_PANEL_ITEMS: 'DELETE_MAIN_PANEL_ITEMS' = 'DELETE_MAIN_PANEL_ITEMS';
export const COPY_MAIN_PANEL_ITEMS: 'COPY_MAIN_PANEL_ITEMS' = 'COPY_MAIN_PANEL_ITEMS';
