export const INVENTORY: 'INVENTORY' = 'INVENTORY';
export const SWAP_INVENTORY_SLOTS: 'SWAP_INVENTORY_SLOTS' = 'SWAP_INVENTORY_SLOTS';
export const INVENTORY_ITEM_SELECTED: 'INVENTORY_ITEM_SELECTED' = 'INVENTORY_ITEM_SELECTED';
