export const DIRECTION_FORWARD: 'DIRECTION_FORWARD' = 'DIRECTION_FORWARD';
export const DIRECTION_BACK: 'DIRECTION_BACK' = 'DIRECTION_BACK';
export const DIRECTION_LEFT: 'DIRECTION_LEFT' = 'DIRECTION_LEFT';
export const DIRECTION_RIGHT: 'DIRECTION_RIGHT' = 'DIRECTION_RIGHT';
