// @flow
export const MOUSE_MOVE: 'MOUSE_MOVE' = 'MOUSE_MOVE';
export const MOUSE_LEFT_BUTTON: 'MOUSE_LEFT_BUTTON' = 'MOUSE_LEFT_BUTTON';
export const MOUSE_MIDDLE_BUTTON: 'MOUSE_MIDDLE_BUTTON' = 'MOUSE_MIDDLE_BUTTON';
export const MOUSE_RIGHT_BUTTON: 'MOUSE_RIGHT_BUTTON' = 'MOUSE_RIGHT_BUTTON';
export const MOUSE_POINTER_UNLOCKED: 'MOUSE_POINTER_UNLOCKED' = 'MOUSE_POINTER_UNLOCKED';
