// @flow
export const CHUNK_LOADED: 'CHUNK_LOADED' = 'CHUNK_LOADED';
export const TERRAIN_REMOVED_BLOCK: 'TERRAIN_REMOVED_BLOCK' = 'TERRAIN_REMOVED_BLOCK';
export const TERRAIN_PLACED_BLOCK: 'TERRAIN_PLACED_BLOCK' = 'TERRAIN_PLACED_BLOCK';
export const TERRAIN_MIPMAP_LOADED: 'TERRAIN_MIPMAP_LOADED' = 'TERRAIN_MIPMAP_LOADED';
