// @flow
export const PLAYER_LOADED: 'PLAYER_LOADED' = 'PLAYER_LOADED';
export const PLAYER_CHANGED_ROTATION: 'PLAYER_CHANGED_ROTATION' = 'PLAYER_CHANGED_ROTATION';
export const PLAYER_JUMPED: 'PLAYER_JUMPED' = 'PLAYER_JUMPED';
export const PLAYER_STOPED_JUMPING: 'PLAYER_STOPED_JUMPING' = 'PLAYER_STOPED_JUMPING';
export const PLAYER_MOVED: 'PLAYER_MOVED' = 'PLAYER_MOVED';
export const PLAYER_STOPED_MOVING: 'PLAYER_STOPED_MOVING' = 'PLAYER_STOPED_MOVING';
export const PLAYER_RUN: 'PLAYER_RUN' = 'PLAYER_RUN';
export const PLAYER_STOPED_RUNING: 'PLAYER_STOPED_RUNING' = 'PLAYER_STOPED_RUNING';
